### ISSUE TITLE
feature request: add possiblility to use loadoing wagons onbaling Contracts

### ISSUE THREAD

**Issue by goldenshoes** [Mmtrx/FS22_BetterContracts#118]
With addition of new DLC it would be nice to be able to use loading wagons and forage wagons on baling contracts to use new stationary balers

**Comment by Mmtrx** [comment]
Ok, I understand. Std game lets you only use mower, tedder, windrower, baler, wrapper.
Here is a quick fix:
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11081650/FS22_BetterContracts.zip)
Drawback: Since you now produce the bales "on your own", the game doesn't recognize wrapped grass bales as "mission bales", and you have to wait the full fermenting time before they switch to silage.
Maybe if you try to produce the bales on the contract field - I couldn't test that (no Göweil dlc yet :)

**Comment by Mmtrx** [comment]
No, because how could the Göweil baler know that it is processing mission grass/ hay?

I am thinking of a little script that could let the player "ferment" a wrapped bale by touching it (analogous to "cut" action). That's just an idea..

**Comment by vitalii2011** [comment]
For the first ~40 bales, it can be fun to "touch", but it will get boring very quickly. AD will become not very "auto". Maybe you can add a switchable "Instant fermentation" function to the technique.
And in itself, the "magic touch" will come in handy in the household. )

**Comment by rohne83** [comment]
Would it be possible to also allow choppers with directdisc or at least pickup? That's a key missing opportunity in the mission system from the beginning.
The game engine doesn't care where the silage for the mission comes from, be it the normal balewrapper, the Göweil baler, a fermenter or a normal bunker silo. So it shouldn't care as well how the field is harvested and the swath collected, by mower+baler, by mower+foragewagon or by chopper.

**Comment by Mmtrx** [comment]
Hi @rohne83,
chopper with pickup should work already. For cutter I need to look..

**Comment by sashaman** [comment]
oh this one really catched me, prolly closely related to one thing that bugs me all the time, i think even since fs19. 
whenever possible, i use the small 120 square bales, 
and since playing with M+ mostly i am able to stack and wrap these up so they can be fermented. 

the issue, and i think this is a bug (ok, oversight?) by giants, is the arcusin Multipack D14. 
its `baleLoader` spec doesnt respect/inherit `isMissionBale` (not in schema) , contrary to `baler` and `baleWrapper`. 
this might be due to the fact, that `isMissionBale` dooesn't really do anything by itself, 
it only tells a function to have a bale insta-fermented (mission) or have it ferment over time (player). 
and since the basegame doesnt offer a wrapper for the 120 nor the 240 bales (ok only that one inlineWrapper for 240, which probably nobody uses lol) this was overseen.

i'll award you a medal if you can make that dang piece drop 240 packedBale with `missionBale="true"`  👯

**Comment by Mmtrx** [comment]
Äh, also der Multipack D14 ist ja kein wrapper, oder? 
`missionBale true` wird vom Baler erzeugt, wenn der Ballen auf einem Missionsfeld entsteht. 

Versteh ich die Anfrage richtig, dass der Multipack den entladenen 240er Ballen `missionBale true` verpasst?
Womit wickelst du denn jetzt die gepackten 240er Ballen?

**Comment by sashaman** [comment]
baler setzt `missionBale="true"`
wickler setzt `missionBale="true"` wenn der ballen es hatte 
der MultiPack setzt kein missionBale, das geht verloren -> der 240 packedBale lässt sich nicht mehr insta gären weil nicht missionBale="true" 

für den normalen gebrauch unerheblich, da die fürn spieler ja gären sollen, aber bei missionen eben nicht. deshalb entsteht das problem das du weiter oben angesprochen hast, die ballen müssten erst gären damit man sie abliefern kann 
die 240er wickel ich mit dem modifizieren kuhn sw4014 der M+ beiliegt, das basisspiel hat da glaub ich nur den schlauchwickler der 240er kann, den hab ich noch nie benutzt

**Comment by rohne83** [comment]
> Hi @rohne83, chopper with pickup should work already. For cutter I need to look..

Just checked, and can confirm. It even works with both now, Pickup and DirectDisc. Very great! Finally investing into a chopper makes economic sense in this game!
