### ISSUE TITLE
"Error: No more interval timers" while enabling the mod with 45 other mods

### ISSUE THREAD

**Issue by Paxol** [Mmtrx/FS22_BetterContracts#14]
I get this error with the version 1.2 (from modhub) and the latest cloned from github (80e6fa4) when I enable the mod in my savegame.
It does not show in the log when I create a new savegame with only this mod, but appears when I create the savegame with all the mods.

I think the relevant lines are:
```
2022-04-19 20:05 Error: Running LUA method 'update'.
dataS/scripts/specialization/TypeManager.lua(228) : attempt to index local 'spec' (a nil value)
2022-04-19 20:05 Error: No more interval timers
```

Complete log [here](https://pastebin.com/raw/0XezxEef)

PS: Using latest FS22 version, patch 1.4

**Comment by powermines** [comment]
following does some shop items not load ?

**Comment by Mmtrx** [comment]
Hi,
that's probably a general problem of FS22 1.4.0. GIANTS wrote in their [forum](https://forum.giants-software.com/viewtopic.php?f=876&t=190708):
`Thanks to your reports we discovered the cause of an issue with scriptmods and will deploy a hotfix as soon as possible.`

Since you are on steam, you could try to go back to 1.3.1: Right-click on game > Betas tab > Choose game version
