### ISSUE TITLE
Mission amount delivered out of sync. Not sure what's causing it.

### ISSUE THREAD

**Issue by coatsy35** [Mmtrx/FS22_BetterContracts#156]
Hi,

I have been using this great mod for a while. Still using the latest modhub version 1.2.7.9 however, I'm playing on the Oaks and i've noticed a few times I have completed the field with leased equipment, however my delivery progress is out of sync with the amount the game says has been delivered and I can't complete the contract and get charged for the missing amount, which is frustrating. Sometimes I lease equipment and also use my own lorry to help deliver to the same place. Could this be causing it? I often have 4 or 5 harvest contracts on the go at the same time. I'm just trying to get to the bottom of what's causing this. Is there any more info I can give you?

I end up using a manager mod to fill my trailers and then tip them, the green writing at the top says a different percentage to what the progress bar on the details on page of the contract says.

**Comment by Mmtrx** [comment]
Hm, could have different reasons, e.g.
- multiple active harvest contracts with same fruit / sellpoint are "delivered" by the game in random order. So it can happen that the delivery part of a contract already is fulfilled (with crop from another field), when you not even have started your combine on the contract field. 
- in some mod maps field boundaries are designed a bit sloppy, so that it is hard to impossible to harvest the amount the contract asks for (std is 93% of the theoretically possible fruit based on the ha area of the field).

So you can try to
- do one harvest contr after the other
- decrease the harvest min delivery percentage:
![settings_harvest](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/3387cde4-8b1e-4d66-a8dd-869949fe161f)

**Comment by coatsy35** [comment]
You are correct, as I tested that last night but hasn’t had chance to report it. It happens if you run multiple harvest contracts running to the same place. This is unfortunate as I enjoy having lots on the go at the same time. I assume this is a giants issue and cannot be fixed? I already do as you suggest with settings  but it can be quite out still. I guess due to very large field sizes on XL maps. Thanks for looking

**Comment by zinni97** [comment]
The easiest "fix" would be to just wait with completing the contracts until you finished all fields that share the same selling point. That way the problem resolves itself, that's how I do it. Other than that the fault is on Giants and probably hard to fix I'd imagine.

**Comment by coatsy35** [comment]
> The easiest "fix" would be to just wait with completing the contracts until you finished all fields that share the same selling point. That way the problem resolves itself, that's how I do it. Other than that the fault is on Giants and probably hard to fix I'd imagine.

I guess if it's confirmed it is Giants I will submit a bug report. Might as well tell them even if they know as more chance for them to fix it!

**Comment by zinni97** [comment]
I just tried it on a vanilla Savegame, it reacts the same way there too, so like assumed it's a Giants bug.
You can try reporting it to Giants, probably will do about the same as if you didn't it, but go ahead and try, good luck you might need it...

**Comment by coatsy35** [comment]
> I just tried it on a vanilla Savegame, it reacts the same way there too, so like assumed it's a Giants bug. You can try reporting it to Giants, probably will do about the same as if you didn't it, but go ahead and try, good luck you might need it...

I have done, just for the kicks 🤣🤣

**Comment by Mmtrx** [comment]
As discussed, not BCs fault😎
