### ISSUE TITLE
Bug for contracts of same type

### ISSUE THREAD

**Issue by Tracas** [Mmtrx/FS22_BetterContracts#219]
Hello,

Since I've been using this mod, I've noticed that if I do 2 contracts of the same type, for example, silage, as soon as I sell the bales from one of the fields, it counts as if it were also for the other contract. In other words, with 2 contracts of the same type, it's enough to complete both contracts, without even starting the second one. For example, if there are 2 silage contracts, one in field 3 and another in field 4, selling the bales from field 3 progresses in the contract for field 4. As soon as I deactivate the mod, none of what I mentioned happens.

Thank you!

**Comment by NathanS-8500** [comment]
Tracas, this behavior is not a bug. It's called job overlapping. For example:

A contract for F 3 harvesting sugar beets going to the Grain Mill is active.

You also have another job of sugar beets on F 5 also going to the Grain Mill. Sugar beets that you have harvested off of F 3 will be assumed when you head to the Grain Mill to unload. The job thinks it's coming from F 5. That's why F 5 assumes the beets are off of the field and shows a percentage on the contract for F 5.

The general rule of thumb, don't accept jobs from two different fields with the same filltype going to the exact same place. This also means you cannot have two cotton jobs active generally unless the place that is asking for the cotton is all together separate for the places the cotton are accepted.

Hope this helps.

**Comment by Tracas** [comment]
Hello @NathanS-8500 
As I mentioned before, since I've been using this mod, if I do 2 identical contracts, this problem occurs, if you remove the mod and repeat the same operation, it doesn't happen.
If you tell me a place where to upload the screenshots and show it, I'll be happy to do so.
Regards :)

**Comment by Mmtrx** [comment]
I think @NathanS-8500 is right. This will happen as well in the base game. 
And you cannot "complete both contracts, without even starting the second one", because even if you deliver enough bales for both, you still have to mow the other field.

**Comment by NathanS-8500** [comment]
> I think @NathanS-8500 is right. This will happen as well in the base game. 
> 
> And you cannot "complete both contracts, without even starting the second one", because even if you deliver enough bales for both, you still have to mow the other field.

Thank you. I knew I was right.
