### ISSUE TITLE
Better Better Contract

### ISSUE THREAD

**Issue by XkalibrX** [Mmtrx/FS22_BetterContracts#39]
Please tell me is it possible to do this?

Big and complex:
Each owner of the fields has his own fields, which are divided between them by hectares.
Each owner has a rating to the player
The rating is obtained by fulfilling his contracts
The rating is taken away under the condition of taking the contract and not fulfilling it
The task is automatically considered not completed after 24 game hours
The purchase of fields is bought for a rating from the owner of the field and money
When purchase a field, the rating is deducted based on the cost for the field.
After all the fields of the owner are gone, he no longer generates tasks
The owner gives equipment for rent only if the rating is below N, after each task is performed only on his own equipment

Simple:
Penalty in the amount of N% of the amount of the contract if the player accepted the task and canceled it or more than 24 game hours have passed

**Comment by Mmtrx** [comment]
Anything is possible, if you are a programmer 😉 
Thanks for the interesting enhancement suggestions. I think I'll incorporate some of that in a future release.
Completing contracts for a given NPC farmer to lower the price of his field was a feature in FS17 (or FS15), I think. You would get 5% off from field price, so after completing 10 contracts you can buy a field at 50%.

**Comment by Mmtrx** [comment]
So I've added most of that, see Version [1.2.5.0beta](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.5.0beta). 
To do:
> 
> The rating is taken away under the condition of taking the contract and not fulfilling it 

Should the rating, i.e. the discount go one step back, or completely to zero? E.g if it was 40% before the cancelled contract, is it now 30% or 0?
> The owner gives equipment for rent only if the rating is below N, after each task is performed only on his own equipment

Do you mean the first missions for an NPC farmer do not offer lease vehicles?

**Comment by cwattyeso** [comment]
Just downloaded the new update but not yet loaded up the game to take a look. My first question is about these two new options:
add option hard mode: active missions time out at midnight. Penalty for mission cancel (suggested in https://github.com/Mmtrx/FS22_BetterContracts/issues/39)
add option discount mode: get discounted field price, based on number of missions (suggested in https://github.com/Mmtrx/FS22_BetterContracts/issues/39)

Can these be turned off easily within the game and just have the Better Contracts mod experience we've come to expect? The reason for this is I feel that some of the suggestions people have been making and some of the recent changes to the mod are now moving it away in a different direction then what the mod was originally supposed to be for. I'm not sure all the recent changes or some of these news ones are actually making for better contracts. I mean adding a hard mode where contracts fail after 24 hours isn't really making the contract system easier for the player and more beneficial.

**Comment by Mmtrx** [comment]
Hi @cwattyeso,
yes, these new options are disabled by default. To activate them, you would need to put `hardMode="true"` or  `discountMode="true"`  (or both) in the settings xml file.

You are absolutely correct, hardMode 
> isn't really making the contract system easier for the player and more beneficial.

But play style is different among the millions of players, some really like challenges (e.g. start-from-zero) 😉.

**Comment by cwattyeso** [comment]
Yes I appreciate people have different playstyles, how one person or a few persons playstyle shouldn't completely change your mod and take it away from the original concept and intention.

For example the recent changes where only Admins can refresh the Contracts screen and generate new contracts, and only being able to have 3 active contracts at a time, completely undoes the purpose of this mod. Better Contracts was supposed to let players refresh their mission list anytime in game, and accept and undertake as many missions as they wanted. The person that wanted the restrictions putting on the contracts, would have been much better off not installing and activating the mod if they just wanted the original vanilla Giants contract experience. So because one player wanted to stop people in multiplayer refreshing contracts and doing more then 3 contracts at a time, you've changed the whole mod which effects every player.

Perhaps you should have put those changes in as optional, meaning players need to turn on the Admin Retrictions and Contract Limit restrictions if they want, but not have those as the default settings for all players who liked how the mod has been working since you first released it.

Also regarding this new change for contracts that fail at midnight. Did you think how this would effect people doing say Sugar Beet Harvesting or Potato Harvesting on large fields using the Mission Offered Vanilla Game Equipment, where it takes several in game days to complete the contract if you're playing with the time scale set on anything above real time. Perhaps you need to exclude some contracts such as Harvesting from this fail state because again if start a contract and then have it fail before they can finish it they will be really annoyed. For example you could have a normal harvesting contract, but then it starts raining in game which prevents the player from being able to continue harvesting. Normally they'd just carry on the following the day when the weather is better. However now they are going to have the contract fail at midnight? That doesn't seem very fair.

Whilst I understand having timers and need to complete contracts in a certain time or day for things like delivery contracts or supply and transport contracts, I don't see how having timers or limits on field work tasks is a good idea, because so many factors can occur that stop you doing something within X Game Hours or Game Day.

**Comment by Mmtrx** [comment]
Hi @cwattyeso,
thanks for the comprehensive feedback, that is valuable information for me.

I am really trying to implement any mod enhancement as optional, the player decides if they want it activated or not. Only exception today is the restriction to Admin rights for refreshing contracts list. Thank you for pointing that out, it will be changed in the next update.

Restriction to 3 active contracts (as in base game) is optional already: You can specify with `maxActive=n` (in the FS22_BetterContracts.xml settings file) an arbitrary number of allowed active contracts.  `maxActive=0` means unlimited, as in earlier versions of the mod.

I know you asked for a different directory (savegame) for the settings file, since it can be hard to access the games /modSettings directory. But there is even better news: I am currently working on an ingame UI (within the ingame menu structure) to let the player change all mod settings, to spare them any file editing hassles.

Regarding the 24-hour time limit for active contracts, I will change that to end-of-month. So with game setting 1day/month, it will stay like it is now. But setting more days per month will give you more time to harvest large fields.

**Comment by cwattyeso** [comment]
Yeah in game UI for accessing and changing settings would be gratefully expected as you continue to expand the mod and add new stuff. That way players like me that just want the original simple functions of unlimited contracts and being able to refresh/generate new contracts whenever can do so without having to changes scripts or xml files. Also for Rented/Hosted Server Managers like me, that can't access Games/Modsettings folder on server to even get to the XML, we will be able to change settings for our multiplayer maps.

**Comment by Yiddan** [comment]
> I will change that to end-of-month.
This is something i was coming to ask, i'm glad this is already in the plans !

> I am currently working on an ingame UI
This is also great :)
I'm not usually tweaking my settings, but i get how this can be painful to "less confident with computer stuff" players

I love this mod, thanks again for all the work you put into it ;)
