### ISSUE TITLE
just a question regarding "time left for mission"

### ISSUE THREAD

**Issue by mrPassion78** [Mmtrx/FS22_BetterContracts#56]
I`m always wondering , how much time i have left to do a mission.. and i cannot find it anywhere.

Sins the missions dissappear after time, there must be some sort of timer inplace, i guess...
 would it be possible to show the max. time for a mission in the details before accepting the mission, or, after you started the mission, that it can be displayed then.

Do not know if it is even possible, just would come in handy as a single player, with multiple missions going. 

thnx in advance for reading 
Pascal

**Comment by Mmtrx** [comment]
Hi Pascal,
this is not possible / not needed for fieldwork missions, because

1. active (started) mission: the mission does not expire, you can keep it for years (new option `hardMode `of BetterContracts cancels it at midnight 😉)
2. offered (not accepted) missions: the game checks at start of every month (i.e. every day at midnight, if you play 1 day/month), if
-- **harvest or sow** is still possible, according to the growth calendar, e.g. if you don't accept a harvest contract within the harvest period of the given crop, the game will take the mission off the list
-- **other fieldwork** can be done by the NPC owner. Based on a random decision, the NPC will do the work, and the game will take the mission off the list. That can also happen for harvest / sow missions.
(You can tweak the random NPC work by `lazyNPC `option of BetterContracts)

**Comment by mrPassion78** [comment]
awesome.. thnx for explaning it.. 
i`m going to try it out.. :D.  sins i have maize + installed, the bales need time to ferment, and in fs19 that time took to long, and my contracts got cancelled, and ended up with near 500 bales needin to be taken acros the map.. LOL. Thats why i asked that :D.
 thnx so much, and i`ll close it now.
