### ISSUE TITLE
Settings for servers

### ISSUE THREAD

**Issue by goldenshoes** [Mmtrx/FS22_BetterContracts#57]
It's not really an issue. Just have a question is there settings xml that turns on and off some settings when you have the mod on dedi server?

Or maybe it would be possible to add these settings into ingame settings menu?

**Comment by Mmtrx** [comment]
Hi,
the settings file is the same as for single player:` FS22_BetterContracts.xml` in /modSettings directory. In a MP game, only this settings file is valid, the mod ignores settings files on the clients.
I have another request to move this file to a savegame directory, because some server providers may not let you access other directories (via ftp for instance).
And yes, I am also thinking about adding a UI to change settings from the ingame menu. That could take a while though ..

**Comment by goldenshoes** [comment]
UI in game would be awesome. For now I'm going to see what can I do on server to change some settings
