### ISSUE TITLE
Update 1.2.7.0 ... some problems for me.

### ISSUE THREAD

**Issue by FatLizard** [Mmtrx/FS22_BetterContracts#96]
Hi, I'm playing on a couple of map at the moment (Osada and Mazowiecka Nizina v3.0).
No issues until the update 1.2.7.0 then something went wrong.
Today I was playing Mazowiecka Map, on 1 March several sowing and fertilization contracts appeared and I picked 3 of them (Potatoes)
During the first the graphics started not to work correctly (Open the Map and there was no menu icons on the left, the numbers of the soils have disappeared almost all) I checked my log.txt and, apart from a few Warnes I had mistakes only concerning, I assume, the mini icons for rolling contracts.  
**C:/Users/fatli/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/options.lua:492: *Error: no icon found for mission type roll 2023-01-30 15:15 Error: Running LUA method 'draw'.**
I came out of the game, I removed the Rolling contracts Mod from loading and I returned to the game. All sowing contracts were finished by the NPC :( and I only had the 3 of the sowing of the potatoes that I already had but graphics issues mentioned above was yet there.
I rolled back to 1.2.6.5. and all is ok.  :)

**Comment by Mmtrx** [comment]
Ok thanks for testing and reporting this. That's a real bug, since I forgot about the Rolling Missions mod. Fix will be in next update.

PS. When you encounter future contract-related bugs, you should also delete the `mission.xml` from the relevant savegame folder, before a restart. In case above, there probably was still a roller mission in that file, that the game (and BetterContracts) could not handle without the Rolling Mod.

**Comment by FatLizard** [comment]
Thanks in advance ... I'll test it tomorrow but I'm sure you have done a great job, as always... :)

**Comment by Mmtrx** [comment]
..seem s to work 😉

**Comment by FatLizard** [comment]
> ..seem s to work 😉

Yes ... sorry but my game time was really a few in the past days.
It works perfectly and now I can appreciate the new features too ... really a great work ! Bravo !
